### ISSUE TITLE
Broken link in docs/templating.md

### ISSUE THREAD

**Issue by lodotek** [kluctl/template-controller#2]
Broken link here:
https://github.com/kluctl/template-controller/blob/main/docs/templating.md?plain=1#L14
And on the website: https://kluctl.io/docs/template-controller/templating/

Broken Link: https://kluctl.io/docs/reference/templating/

**Comment by codablock** [comment]
Thanks for reporting. This is fixed in the repo now and the next release will cause it to be synced to the website.
