### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by pierDipi** [kluctl/template-controller#56]
This repository is missing a LICENSE file, I assume it should be the same as core kluctl https://github.com/kluctl/kluctl/blob/main/LICENSE  ?

**Comment by codablock** [comment]
You're right @pierDipi, it's missing as it seems. I might have forgotten to add it in the beginning. I'll fix this when I find time. As an alternative, I'd be happy to get a PR :)

**Comment by pierDipi** [comment]
PR: https://github.com/kluctl/template-controller/pull/57
